### ISSUE TITLE
avoid using loop

### ISSUE THREAD

**Issue by ayoubbouih** [ahmedosama-st/php-mvc-project#2]
I think it will be better to avoid the for loop in MySQLGrammar::buildInsertQuery method,
by using the code:
`

       
        $arr = array_fill(0,sizeof($keys),'?');
        $values = implode(" , ",$arr);
        return "insert into ".Model::getTableName()." (`".implode('`,`',$keys)."`) values(".$values.")";
`
instead of:
`

        $values = '';
        for ($i = 0; $i < count($keys); $i++) {
            $values .= '?, ';
        }

        $query = 'INSERT INTO ' . Model::getTableName() . ' (`' . implode('`, `', $keys) . '`) VALUES(' . rtrim($values, ', ') . ')';

        return $query;
`
 it's just a proposition to more optimize the code
Thank you so much for the course, waiting your new content

**Comment by ahmedosama-st** [comment]
I've tested your solution, it seems to be working fine, However, I tend to keep the implementation the same to keep consistency around all `MySQLGrammar` functionality.

Regardless, good job of thinking of such a solution.
